apiVersion: v1
kind: Secret
metadata:
  name: sql-server-credentials
  namespace: cdc-system
type: Opaque
stringData:
  SA_PASSWORD: "YourSecureP@ssw0rd!"
  ACCEPT_EULA: "Y"
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: cdc-system
type: Opaque
stringData:
  RABBITMQ_DEFAULT_USER: admin
  RABBITMQ_DEFAULT_PASS: "rabbitmq-securepass123"
---
apiVersion: v1
kind: Secret
metadata:
  name: debezium-credentials
  namespace: cdc-system
type: Opaque
stringData:
  database_user: sa
  database_password: "YourSecureP@ssw0rd!"
